---
title: "Python üêç : Manejo de Errores y Excepciones"
author: enidev911
categories: [Python, "02. Intermedio"]
tags: [python, intermedio]
mermaid: true
---

El manejo de errores y excepciones es una parte fundamental en el desarrollo de cualquier software, y Python proporciona una manera eficiente y flexible de gestionar situaciones imprevistas que pueden surgir durante la ejecuci√≥n de un programa. En este art√≠culo, exploraremos c√≥mo funcionan las excepciones en Python y c√≥mo podemos usarlas para hacer que el c√≥digo sea m√°s robusto y f√°cil de depurar.

## **¬øQu√© es una Excepci√≥n?**

En t√©rminos sencillos, una excepci√≥n es un evento inesperado que interrumpe el flujo normal de ejecuci√≥n de un programa. En Python, las excepciones se utilizan para manejar errores de forma controlada, permitiendo que el programa no se detenga bruscamente.

Por ejemplo, si intentas dividir por cero, Python lanzar√° una excepci√≥n [`ZeroDivisionError`](https://docs.python.org/3/library/exceptions.html#ZeroDivisionError){: target='_blank' }. En lugar de que el programa se detenga de inmediato, podemos **capturar** y manejar esa excepci√≥n para tomar una acci√≥n apropiada, como mostrar un mensaje de error o realizar una operaci√≥n alternativa.


## **Estructura B√°sica de Manejo de Excepciones**

En Python, el manejo de excepciones se realiza mediante las plabaras claves `try`, `except`, y opcionalmente `else` y `finally`. Y funciona de la siguiente manera:

```mermaid
flowchart TD
    A([Inicio]) --> B{<font size="6">TRY</font><br>¬øOcurre una excepci√≥n?}
    B -- No --> C[<font size="5">ELSE</font><br>Ejecutar bloque de c√≥digo]
    B -- S√≠ --> D[<font size="5">EXCEPT</font><br>Capturar excepci√≥n]
    C --> E[<font size="5">FINALLY</font><br>Ejecutar bloque finally]
    D --> E
    E --> F([Fin])
```

**Sintaxis B√°sica**

```py
try:
    # Bloque de c√≥digo que puede causar una excepci√≥n
    resultado = 10 / 0
except ZeroDivisionError as e:
    # Bloque que maneja la excepci√≥n
    print(f"Error: {e}")
```
{: .nolineno }

En este ejemplo:

- El bloque `try` contiene el c√≥digo que podr√≠a generar una excepci√≥n.
- Si ocurre una excepci√≥n, Python salta al bloque `except` donde puedas manejarla. En este caso, capturamos una excepci√≥n de tipo `ZeroDivisionError` y mostramos un mensaje de error.

### **Bloque else**

El bloque `else` es opcional y se ejecuta solo si no se ha producido ninguna excepci√≥n en el bloque `try`. Es √∫til en diferentes contextos para ejecutar c√≥digo que dependa de que no haya errores.

```py
try:
    x = 10 / 2
except ZeroDivisionError:
    print("No se puede dividir por cero.")
else:
    print(f"La operaci√≥n fue exitosa: {x}")
```
{: .nolineno }

En este caso, si no ocurre ninguna excepci√≥n en el bloque `try`, el bloque `else` se ejecutar√°, mostrando el resultado de la operaci√≥n.

## **Tipos de Excepciones**

Python tiene muchas excepciones m√°s, pero esta tabla cubre las m√°s comunes y √∫tiles para el manejo de errores. 

| **Excepci√≥n**| **Descripci√≥n**|
|:-------------|:---------------|
|`BaseException`|La clase base para todas las excepciones.|
|`Exception`|Clase base para todas las excepciones est√°ndar.|
|`ArithmeticError`|Clase base para los errores aritm√©ticos, como `ZeroDivisionError` o `OverflowError`.|
|`ZeroDivisionError`|Se lanza cuando se intenta dividir un n√∫mero por cero.|
|`OverflowError`|Se lanza cuando un n√∫mero excede el l√≠mite permitido por el sistema.|
|`ValueError`|Se lanza cuando una operaci√≥n o funci√≥n recibe un argumento con un valor inapropiado.|
|`IndexError`|Ocurre cuando se intenta acceder a un √≠ndice de lista o secuencia fuera de su rango.|
|`KeyError`|Se lanza cuando se intenta acceder a una clave que no existe en un diccionario.|
|`TypeError`|Se lanza cuando una operaci√≥n o funci√≥n es aplicada a un objeto de tipo inapropiado.|
|`FileNotFoundError`|Ocurre cuando se intenta abrir un archivo que no existe.|
|`IOError`|Se lanza cuando ocurre un error de entrada/salida, como al leer o escribir archivos.|
|`ValueError`|Se lanza cuando se pasa un valor incorrecto a una funci√≥n.|
|`ImportError`|Ocurre cuando un m√≥dulo o funci√≥n no se puede.|
|`ModuleNotFoundError`|Se lanza cuando el m√≥dulo solicitado no se puede encontrar.|
|`AttributeError`|Se lanza cuando un objeto no tiene el atributo solicitado.|
|`NameError`|Se lanza cuando se hace referencia a una variable que no est√° definida.|
|`SyntaxError`|Se lanza cuando hay un error de sintaxis en el c√≥digo, es decir, cuando el c√≥digo no sigue las reglas del lenguaje.|
|`IndentationError`|Subclase de `SyntaxError` que ocurre cuando hay un error de indentaci√≥n en el c√≥digo.|
|`AssertionError`|Se lanza cuando una afirmaci√≥n (`assert`) falla, es decir, cuando una expresi√≥n booleana es falsa.|
|`MemoryError`|Ocurre cuando se agota la memoria disponible.|
|`RecursionError`|Se lanza cuando se excede el l√≠mite de recursi√≥n en el c√≥digo.|
|`NotImplementedError`|Se lanza cuando una funci√≥n o m√©todo no est√° implementado, pero est√° presente en la interfaz.|
|`TimeoutError`|Ocurre cuando una operaci√≥n supera el tiempo de espera establecido.|
|`KeyboardInterrupt`|Se lanza cuando el usuario interrumpe la ejecuci√≥n del programa mediante la pulsaci√≥n de <kbd>Ctrl</kbd>+<kbd>C</kbd>.|
|`StopIteration`|Se lanza para indicar que no hay m√°s elementos en un iterador.|
|`StopAsyncIteration`|Se lanza para indicar que no hay m√°s elementos en un iterador as√≠ncrono.|
|`ConnectionError`|Clase base para errores relacionados con la red o las conexiones.|
|`TimeoutError`|Se lanza cuando una operaci√≥n excede el tiempo de espera.|

### **Algunas excepciones adicionales menos comunes**

- `UnicodeDecodeError` ‚Äì Ocurre cuando falla la decodificaci√≥n de una cadena Unicode.
- `UnicodeEncodeError` ‚Äì Ocurre cuando falla la codificaci√≥n de una cadena Unicode.
- `DeprecationWarning` ‚Äì Advertencia sobre el uso de caracter√≠sticas obsoletas.
- `UserWarning` ‚Äì Advertencia general que puede ser utilizada para notificar al usuario sobre condiciones de advertencia.

### **Excepci√≥n Gen√©rica**

Si no sabemos qu√© tipo de excepci√≥n puede ocurrir o si deseas capturar cualquier tipo de error, podemos usar un bloque `except` sin especificar una excepci√≥n:

```py
try:
    x = 10 / 0
except Exception as e:
    print(f"Ocurri√≥ un error: {e}")
```
{: .nolineno }

Usar `Exception` es √∫til cuando no est√°s seguro de qu√© tipo de excepci√≥n puede ocurrir.

> Se recomienda siempre que sea posible usar excepciones espec√≠ficas para un manejo de errores m√°s preciso.
{: .prompt-tip }

## **Manejar M√∫ltiples Excepciones**

Podemos manejar diferentes tipos de excepciones con m√∫ltiples bloques `except`. Si tenemos varios casos de error posibles, podemos especificarlos de forma individual de la siguiente manera:

```py
try:
    valor = int(input("Introduce un n√∫mero: "))
    resultado = 10 / valor
except ZeroDivisionError:
    print("No puedes dividir por cero.")
except ValueError:
    print("Eso no es un n√∫mero v√°lido.")
```
{: .nolineno }

## **Levantar Excepciones Personalizadas**

Python nos permite crear y lanzar nuestras propias excepciones utilizando la palabra clave `raise`. Esto es √∫til cuando deseamos controlar el flujo de ejecuci√≥n en situaciones espec√≠ficas, como validaciones personalizadas.

**Ejemplo de Excepci√≥n personalizada**

```py
class MiExcepcion(Exception):
    pass

def dividir(a, b):
    if b == 0:
        raise MiExcepcion("No se puede dividir por cero")
    return a / b

try:
    resultado = dividir(10, 0)
except MiExcepcion as e:
    print(f"Error: {e}")
```
{: .nolineno }

